# Generated by Django 2.1.7 on 2019-02-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190211_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of submission'),
        ),
    ]
